config/routes.rb
Blog::Application.routes.draw do
  get "welcome/index"

  root to: 'welcome#index'

  resources :posts do 
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :body, :commenter
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :name, :title, :tags_attributes

  validates :name, presence: true
  validates :title, presence: true,
                    length: { minimum: 5}

  has_many :comments, dependent: :destroy
  has_many :tags

  accepts_nested_attributes_for :tags, allow_destroy: :true, reject_if: proc {|attrs| attrs.all? {|k, v| v.blank?}}
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :post
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: 'ameen', password: 'qweqweqwe', only: [:destroy]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment])
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  http_basic_authenticate_with name: 'ameen', password: 'qweqweqwe', except: [:index, :show]

  def index
    @posts = Post.all

    respond_to do |format|
      format.html  # index.html.erb
      format.json  { render :json => @posts }
    end
  end

  def new
    @post = Post.new
  end
  
  def show
    @post = Post.find(params[:id])
  end

  def create
    # render text: params[:post].inspect
    # @post = Post.new(post_params.permit(:title, :text))
    @post = Post.new(params[:post])
    
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(params[:post])
      redirect_to post_path
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    
    redirect_to posts_path
  end


  # private

  #   def post_params
  #     params.require(:post).permit(:title, :text)
  #   end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def join_tags(post)
    post.tags.map { |t| t.name}.join(", ")
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.slim
p
  b Commenter:
  = comment.commenter
p
  b Comment:
  = comment.body
p
  = link_to 'Delete Comment', [comment.post, comment],
            confirm: 'Are you sure?',
            method: :delete

app/views/comments/_form.html.slim
= form_for ([@post, @post.comments.build]) do |f|
  .field
    = f.label :commenter
    = f.text_field :commenter
  .field
    = f.label :body
    = f.text_area :body
  .actions
    = f.submit
  end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.slim
- @post.tags.build
= form_for (@post) do |post_form|
  / - if @post.errors.any?
  /   #errorExplanation
  /     h2
  /       = pluralize(@post.errors.count, "error")
  /       | prohibited this post from being saved:
  /     ul
  /       - @post.errors.full_messages.each do |msg|
  /         li = msg
  = post_form.error_messages
  .field
    = post_form.label :name
    br/
    = post_form.text_field :name
  .field
    = post_form.label :title
    br/
    = post_form.text_field :title
  .field
    = post_form.label :content
    br/
    = post_form.text_area :content

    h2 Tags
    = render partial: 'tags/form',
              locals: {form: post_form}
  .actions
    = post_form.submit

app/views/posts/edit.html.slim
/ h1 Edit Post
/ = form_for :post, url: edit_posts_path(@post.id), method: :put do |f|
/   p
/     = f.label :title 
/     br
/     = f.text_field :title 
/     br

/   p
/     = f.label :text 
/     br
/     = f.text_area :text 
/     br

/   p
/     = f.submit
/ end

h1 Editing post
/ = form_for :post, url: post_path(@post.id), method: :put do |f|
/   p
/     = f.label :title
/     br
/     = f.text_field :title
/   p
/     = f.label :name
/     br
/     = f.text_field :name
/   p
/     = f.label :text
/     br
/     = f.text_area :text
/   p
/     = f.submit 'Update'
= render 'form'

  = link_to 'Back', posts_path

/ = link_to 'Back to all Posts', posts_path

app/views/posts/index.html.slim
h1 Listing all Posts

table
  tr
    th Title
    th Posts
    th Name

  - @posts.each do |post|
    tr
      td = post.title
      td = post.content
      td = post.name
      td = link_to 'Show post', post_path(post)
      td = link_to 'Edit post', edit_post_path(post)
      td = link_to 'Delete post', post_path(post), confirm: 'Are you sure?', method: :delete
    end

p 
  = link_to 'Create a new Post', new_post_path

app/views/posts/new.html.slim
h1 New Post
/ = form_for :post, url: posts_path do |f|
  / -if @post.errors.any?
  / #errorExplanation
  /   h2 = pluralize(@post.errors.count, "error") 
  /     |prohibited this post from being saved
  /   ul
  /   -@post.errors.full_messages.each do |msg|
  /     li = msg
/   p
/     = f.label :title 
/     br
/     = f.text_field :title 
/     br
/   p
/     = f.label :name
/     br
/     = f.text_field :name

/   p
/     = f.label :text 
/     br
/     = f.text_area :text 
/     br

/   p
/     = f.submit
/ end

= render 'form'

p 
  = link_to 'Back to all Posts', posts_path

app/views/posts/show.html.slim
p#notice = notice
h1 Post

p
  strong Title:
  = @post.title
p
  strong Name:
  = @post.name
p
  strong Content:
  = @post.content
p
  b Tags:
  = join_tags(@post)

h2 Comments
= render @post.comments

h2 Add a Comment
= render 'comments/form'

p
  = link_to 'Edit this Post', edit_post_path
p
  = link_to 'Back to all Posts', posts_path

app/views/tags/_form.html.slim
= form.fields_for :tags do |tag_form|
  .field
    = tag_form.label :name, 'Tag:'
    = tag_form.text_field :name
  - unless tag_form.object.nil? || tag_form.object.new_record?
    .field
      = tag_form.label :_destroy, 'Remove:'
      = tag_form.check_box :_destroy

app/views/welcome/index.html.slim
h1 Hello, Rails!
= link_to 'My Blog', controller: 'posts'